// GENERATED - do not edit by hand. Rebuild: node tools/harvest-signatures.mjs && npm run format
// The per-NAME function docs table for duckdb (issue #34), parallel to the signature table:
// docUrl points at the vendor's published page for the same source the signature harvest read;
// description (where present) is origin-tagged prose. Same lowercased-name keys as *_SIGNATURES.
// Built 2026-07-14. 405 names (0 with descriptions).
import type { FnDoc } from "../signature/docs.js";

export const DUCKDB_FN_DOCS: Record<string, FnDoc> = {
	abs: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	acos: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	acosh: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	add: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	age: { docUrl: "https://duckdb.org/docs/current/sql/functions/timestamp.html", origin: "vendor-docs" },
	ago: { docUrl: "https://duckdb.org/docs/current/sql/functions/timestamp.html", origin: "vendor-docs" },
	alias: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	any_value: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	arg_max: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	arg_max_null: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	arg_min: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	arg_min_null: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	array_cosine_distance: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/array.html",
		origin: "vendor-docs",
	},
	array_cosine_similarity: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/array.html",
		origin: "vendor-docs",
	},
	array_cross_product: { docUrl: "https://duckdb.org/docs/current/sql/functions/array.html", origin: "vendor-docs" },
	array_distance: { docUrl: "https://duckdb.org/docs/current/sql/functions/array.html", origin: "vendor-docs" },
	array_extract: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	array_inner_product: { docUrl: "https://duckdb.org/docs/current/sql/functions/array.html", origin: "vendor-docs" },
	array_negative_inner_product: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/array.html",
		origin: "vendor-docs",
	},
	array_pop_back: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	array_pop_front: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	array_push_front: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	array_slice: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	array_to_string: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	array_to_string_comma_default: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/list.html",
		origin: "vendor-docs",
	},
	array_value: { docUrl: "https://duckdb.org/docs/current/sql/functions/array.html", origin: "vendor-docs" },
	ascii: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	asin: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	asinh: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	atan: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	atan2: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	atanh: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	avg: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	bar: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	bin: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	bit_and: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	bit_count: { docUrl: "https://duckdb.org/docs/current/sql/functions/bitstring.html", origin: "vendor-docs" },
	bit_length: { docUrl: "https://duckdb.org/docs/current/sql/functions/bitstring.html", origin: "vendor-docs" },
	bit_or: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	bit_position: { docUrl: "https://duckdb.org/docs/current/sql/functions/bitstring.html", origin: "vendor-docs" },
	bit_xor: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	bitstring: { docUrl: "https://duckdb.org/docs/current/sql/functions/bitstring.html", origin: "vendor-docs" },
	bitstring_agg: { docUrl: "https://duckdb.org/docs/current/sql/functions/bitstring.html", origin: "vendor-docs" },
	bool_and: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	bool_or: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	can_cast_implicitly: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html",
		origin: "vendor-docs",
	},
	cardinality: { docUrl: "https://duckdb.org/docs/current/sql/functions/map.html", origin: "vendor-docs" },
	cbrt: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	ceil: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	ceiling: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	century: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	checkpoint: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	chr: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	coalesce: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	concat: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	constant_or_null: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	contains: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	corr: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	cos: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	cot: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	count: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	count_if: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	countif: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	covar_pop: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	covar_samp: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	current_catalog: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	current_database: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	current_localtime: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/timestamptz.html",
		origin: "vendor-docs",
	},
	current_localtimestamp: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/timestamp.html",
		origin: "vendor-docs",
	},
	current_query: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	current_schema: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	current_schemas: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	damerau_levenshtein: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	date_add: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	date_diff: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	date_part: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	date_sub: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	date_trunc: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	datepart: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	day: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	dayname: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	dayofmonth: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	dayofweek: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	dayofyear: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	days_in_month: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	decade: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	decode: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	degrees: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	dense_rank: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/window_functions.html",
		origin: "vendor-docs",
	},
	divide: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	element_at: { docUrl: "https://duckdb.org/docs/current/sql/functions/map.html", origin: "vendor-docs" },
	encode: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	entropy: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	enum_code: { docUrl: "https://duckdb.org/docs/current/sql/functions/enum.html", origin: "vendor-docs" },
	enum_first: { docUrl: "https://duckdb.org/docs/current/sql/functions/enum.html", origin: "vendor-docs" },
	enum_last: { docUrl: "https://duckdb.org/docs/current/sql/functions/enum.html", origin: "vendor-docs" },
	enum_range: { docUrl: "https://duckdb.org/docs/current/sql/functions/enum.html", origin: "vendor-docs" },
	enum_range_boundary: { docUrl: "https://duckdb.org/docs/current/sql/functions/enum.html", origin: "vendor-docs" },
	epoch: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	epoch_ms: { docUrl: "https://duckdb.org/docs/current/sql/functions/timestamp.html", origin: "vendor-docs" },
	epoch_ns: { docUrl: "https://duckdb.org/docs/current/sql/functions/timestamp.html", origin: "vendor-docs" },
	epoch_us: { docUrl: "https://duckdb.org/docs/current/sql/functions/timestamp.html", origin: "vendor-docs" },
	era: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	error: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	even: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	exp: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	factorial: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	favg: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	fdiv: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	first: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	flatten: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	floor: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	fmod: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	force_checkpoint: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	format: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	format_bytes: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	formatreadabledecimalsize: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/text.html",
		origin: "vendor-docs",
	},
	from_base64: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	fsum: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	gamma: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	gcd: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	gen_random_uuid: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	generate_series: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	generate_subscripts: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	geometric_mean: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	get_bit: { docUrl: "https://duckdb.org/docs/current/sql/functions/bitstring.html", origin: "vendor-docs" },
	get_current_time: { docUrl: "https://duckdb.org/docs/current/sql/functions/time.html", origin: "vendor-docs" },
	get_current_timestamp: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/timestamptz.html",
		origin: "vendor-docs",
	},
	getenv: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	glob: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	greatest: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	greatest_common_divisor: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html",
		origin: "vendor-docs",
	},
	hamming: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	hash: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	hex: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	histogram: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	histogram_exact: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	histogram_values: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html",
		origin: "vendor-docs",
	},
	hour: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	icu_sort_key: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	ifnull: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	ilike_escape: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	instr: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	is_histogram_other_bin: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html",
		origin: "vendor-docs",
	},
	isfinite: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	isinf: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	isnan: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	isodow: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	isoyear: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	jaccard: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	jaro_similarity: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	jaro_winkler_similarity: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/text.html",
		origin: "vendor-docs",
	},
	julian: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	kurtosis: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	kurtosis_pop: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	last: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	last_day: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	lcm: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	least: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	least_common_multiple: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html",
		origin: "vendor-docs",
	},
	left: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	left_grapheme: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	length: { docUrl: "https://duckdb.org/docs/current/sql/functions/bitstring.html", origin: "vendor-docs" },
	length_grapheme: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	levenshtein: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	lgamma: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	like_escape: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	list: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	list_aggregate: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_any_value: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_append: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_approx_count_distinct: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/list.html",
		origin: "vendor-docs",
	},
	list_avg: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_bit_and: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_bit_or: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_bit_xor: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_bool_and: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_bool_or: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_contains: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_cosine_distance: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_cosine_similarity: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/list.html",
		origin: "vendor-docs",
	},
	list_count: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_distance: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_distinct: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_entropy: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_extract: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_first: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_grade_up: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_has_all: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_has_any: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_histogram: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_inner_product: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_intersect: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_kurtosis: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_kurtosis_pop: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_last: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_mad: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_max: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_median: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_min: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_mode: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_negative_inner_product: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/list.html",
		origin: "vendor-docs",
	},
	list_position: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_prepend: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_product: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_reverse: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_reverse_sort: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_select: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_sem: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_skewness: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_slice: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_sort: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_stddev_pop: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_stddev_samp: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_string_agg: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_sum: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_unique: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_value: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_var_pop: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_var_samp: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	list_where: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	ln: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	log: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	log10: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	log2: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	lower: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	lpad: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	ltrim: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	mad: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	make_date: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	make_time: { docUrl: "https://duckdb.org/docs/current/sql/functions/time.html", origin: "vendor-docs" },
	make_timestamp: { docUrl: "https://duckdb.org/docs/current/sql/functions/timestamp.html", origin: "vendor-docs" },
	make_timestamp_ms: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/timestamp.html",
		origin: "vendor-docs",
	},
	make_timestamp_ns: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/timestamp.html",
		origin: "vendor-docs",
	},
	make_timestamptz: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/timestamptz.html",
		origin: "vendor-docs",
	},
	map_contains: { docUrl: "https://duckdb.org/docs/current/sql/functions/map.html", origin: "vendor-docs" },
	map_contains_entry: { docUrl: "https://duckdb.org/docs/current/sql/functions/map.html", origin: "vendor-docs" },
	map_contains_value: { docUrl: "https://duckdb.org/docs/current/sql/functions/map.html", origin: "vendor-docs" },
	map_entries: { docUrl: "https://duckdb.org/docs/current/sql/functions/map.html", origin: "vendor-docs" },
	map_extract: { docUrl: "https://duckdb.org/docs/current/sql/functions/map.html", origin: "vendor-docs" },
	map_extract_value: { docUrl: "https://duckdb.org/docs/current/sql/functions/map.html", origin: "vendor-docs" },
	map_keys: { docUrl: "https://duckdb.org/docs/current/sql/functions/map.html", origin: "vendor-docs" },
	map_values: { docUrl: "https://duckdb.org/docs/current/sql/functions/map.html", origin: "vendor-docs" },
	max: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	md5: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	md5_number: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	md5_number_lower: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	md5_number_upper: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	median: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	microsecond: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	millennium: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	millisecond: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	min: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	minute: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	mode: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	month: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	monthname: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	multiply: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	nextafter: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	nfc_normalize: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	not_ilike_escape: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	not_like_escape: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	now: { docUrl: "https://duckdb.org/docs/current/sql/functions/timestamptz.html", origin: "vendor-docs" },
	nullif: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	octet_length: { docUrl: "https://duckdb.org/docs/current/sql/functions/bitstring.html", origin: "vendor-docs" },
	parse_dirname: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	parse_dirpath: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	parse_filename: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	parse_formatted_bytes: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html",
		origin: "vendor-docs",
	},
	parse_path: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	pg_typeof: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	pi: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	pow: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	power: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	prefix: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	printf: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	product: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	quantile_cont: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	quantile_disc: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	quarter: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	query: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	query_table: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	radians: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	random: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	range: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	read_blob: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	read_text: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	regexp_escape: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	regexp_extract: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/regular_expressions.html",
		origin: "vendor-docs",
	},
	regexp_extract_all: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/regular_expressions.html",
		origin: "vendor-docs",
	},
	regexp_full_match: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/regular_expressions.html",
		origin: "vendor-docs",
	},
	regexp_matches: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/regular_expressions.html",
		origin: "vendor-docs",
	},
	regexp_replace: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/regular_expressions.html",
		origin: "vendor-docs",
	},
	regexp_split_to_array: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/regular_expressions.html",
		origin: "vendor-docs",
	},
	regexp_split_to_table: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/regular_expressions.html",
		origin: "vendor-docs",
	},
	regr_avgx: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	regr_avgy: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	regr_count: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	regr_intercept: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	regr_r2: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	regr_slope: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	regr_sxx: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	regr_sxy: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	regr_syy: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	repeat: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	repeat_row: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	replace: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	replace_type: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	reverse: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	right: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	right_grapheme: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	round: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	round_even: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	roundbankers: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	row: { docUrl: "https://duckdb.org/docs/current/sql/functions/struct.html", origin: "vendor-docs" },
	rpad: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	rtrim: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	second: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	sem: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	set_bit: { docUrl: "https://duckdb.org/docs/current/sql/functions/bitstring.html", origin: "vendor-docs" },
	setseed: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	sha1: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	sha256: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	sign: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	signbit: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	sin: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	skewness: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	sleep_ms: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	split_part: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	sqrt: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	starts_with: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	stats: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	stddev_pop: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	stddev_samp: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	strftime: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	string_agg: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	string_split: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	string_split_regex: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	strip_accents: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	strlen: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	strptime: { docUrl: "https://duckdb.org/docs/current/sql/functions/timestamp.html", origin: "vendor-docs" },
	struct_contains: { docUrl: "https://duckdb.org/docs/current/sql/functions/struct.html", origin: "vendor-docs" },
	struct_extract: { docUrl: "https://duckdb.org/docs/current/sql/functions/struct.html", origin: "vendor-docs" },
	struct_extract_at: { docUrl: "https://duckdb.org/docs/current/sql/functions/struct.html", origin: "vendor-docs" },
	struct_position: { docUrl: "https://duckdb.org/docs/current/sql/functions/struct.html", origin: "vendor-docs" },
	struct_values: { docUrl: "https://duckdb.org/docs/current/sql/functions/struct.html", origin: "vendor-docs" },
	substring: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	substring_grapheme: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	subtract: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	suffix: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	sum: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	tan: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	time_bucket: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	timetz_byte_comparable: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/timestamptz.html",
		origin: "vendor-docs",
	},
	timezone: { docUrl: "https://duckdb.org/docs/current/sql/functions/timestamptz.html", origin: "vendor-docs" },
	timezone_hour: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	timezone_minute: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	to_base: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	to_base64: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	to_centuries: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_days: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_decades: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_hours: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_microseconds: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_millennia: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_milliseconds: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_minutes: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_months: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_quarters: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_seconds: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_timestamp: { docUrl: "https://duckdb.org/docs/current/sql/functions/timestamptz.html", origin: "vendor-docs" },
	to_weeks: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	to_years: { docUrl: "https://duckdb.org/docs/current/sql/functions/interval.html", origin: "vendor-docs" },
	today: { docUrl: "https://duckdb.org/docs/current/sql/functions/date.html", origin: "vendor-docs" },
	transaction_timestamp: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/timestamptz.html",
		origin: "vendor-docs",
	},
	translate: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	trim: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	trunc: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	try_strptime: { docUrl: "https://duckdb.org/docs/current/sql/functions/timestamp.html", origin: "vendor-docs" },
	txid_current: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	typeof: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	unbin: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	unhex: { docUrl: "https://duckdb.org/docs/current/sql/functions/blob.html", origin: "vendor-docs" },
	unicode: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	union_tag: { docUrl: "https://duckdb.org/docs/current/sql/functions/union.html", origin: "vendor-docs" },
	unnest: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	unpivot_list: { docUrl: "https://duckdb.org/docs/current/sql/functions/list.html", origin: "vendor-docs" },
	upper: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	url_decode: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	url_encode: { docUrl: "https://duckdb.org/docs/current/sql/functions/text.html", origin: "vendor-docs" },
	uuid: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	uuid_extract_timestamp: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html",
		origin: "vendor-docs",
	},
	uuid_extract_version: {
		docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html",
		origin: "vendor-docs",
	},
	uuidv4: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	uuidv7: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	var_pop: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	var_samp: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	version: { docUrl: "https://duckdb.org/docs/current/sql/functions/utility.html", origin: "vendor-docs" },
	week: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	weekday: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	weekofyear: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	weighted_avg: { docUrl: "https://duckdb.org/docs/current/sql/functions/aggregates.html", origin: "vendor-docs" },
	xor: { docUrl: "https://duckdb.org/docs/current/sql/functions/numeric.html", origin: "vendor-docs" },
	year: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
	yearweek: { docUrl: "https://duckdb.org/docs/current/sql/functions/datepart.html", origin: "vendor-docs" },
};
