// GENERATED - do not edit by hand. Rebuild: node tools/harvest-signatures.mjs && npm run format
// The per-NAME function docs table for trino (issue #34), parallel to the signature table:
// docUrl points at the vendor's published page for the same source the signature harvest read;
// description (where present) is origin-tagged prose. Same lowercased-name keys as *_SIGNATURES.
// Built 2026-07-14. 381 names (0 with descriptions).
import type { FnDoc } from "../signature/docs.js";

export const TRINO_FN_DOCS: Record<string, FnDoc> = {
	abs: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	acos: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	ai_analyze_sentiment: { docUrl: "https://trino.io/docs/current/functions/ai.html", origin: "vendor-docs" },
	ai_classify: { docUrl: "https://trino.io/docs/current/functions/ai.html", origin: "vendor-docs" },
	ai_extract: { docUrl: "https://trino.io/docs/current/functions/ai.html", origin: "vendor-docs" },
	ai_fix_grammar: { docUrl: "https://trino.io/docs/current/functions/ai.html", origin: "vendor-docs" },
	ai_gen: { docUrl: "https://trino.io/docs/current/functions/ai.html", origin: "vendor-docs" },
	ai_mask: { docUrl: "https://trino.io/docs/current/functions/ai.html", origin: "vendor-docs" },
	ai_translate: { docUrl: "https://trino.io/docs/current/functions/ai.html", origin: "vendor-docs" },
	any_value: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	approx_distinct: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	approx_most_frequent: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	approx_percentile: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	approx_set: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	arbitrary: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	array_agg: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	array_distinct: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	array_except: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	array_histogram: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	array_intersect: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	array_join: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	array_max: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	array_min: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	array_position: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	array_remove: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	array_sort: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	array_union: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	arrays_overlap: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	asin: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	atan: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	atan2: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	avg: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	bar: { docUrl: "https://trino.io/docs/current/functions/color.html", origin: "vendor-docs" },
	beta_cdf: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	bing_tile: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	bing_tile_at: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	bing_tile_coordinates: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	bing_tile_polygon: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	bing_tile_quadkey: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	bing_tile_zoom_level: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	bing_tiles_around: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	bit_count: { docUrl: "https://trino.io/docs/current/functions/bitwise.html", origin: "vendor-docs" },
	bitwise_and: { docUrl: "https://trino.io/docs/current/functions/bitwise.html", origin: "vendor-docs" },
	bitwise_and_agg: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	bitwise_left_shift: { docUrl: "https://trino.io/docs/current/functions/bitwise.html", origin: "vendor-docs" },
	bitwise_not: { docUrl: "https://trino.io/docs/current/functions/bitwise.html", origin: "vendor-docs" },
	bitwise_or: { docUrl: "https://trino.io/docs/current/functions/bitwise.html", origin: "vendor-docs" },
	bitwise_or_agg: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	bitwise_right_shift: { docUrl: "https://trino.io/docs/current/functions/bitwise.html", origin: "vendor-docs" },
	bitwise_right_shift_arithmetic: {
		docUrl: "https://trino.io/docs/current/functions/bitwise.html",
		origin: "vendor-docs",
	},
	bitwise_xor: { docUrl: "https://trino.io/docs/current/functions/bitwise.html", origin: "vendor-docs" },
	bitwise_xor_agg: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	bool_and: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	bool_or: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	cardinality: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	cbrt: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	ceil: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	ceiling: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	char2hexint: { docUrl: "https://trino.io/docs/current/functions/teradata.html", origin: "vendor-docs" },
	checksum: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	chr: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	classify: { docUrl: "https://trino.io/docs/current/functions/ml.html", origin: "vendor-docs" },
	coalesce: { docUrl: "https://trino.io/docs/current/functions/conditional.html", origin: "vendor-docs" },
	codepoint: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	color: { docUrl: "https://trino.io/docs/current/functions/color.html", origin: "vendor-docs" },
	contains: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	contains_sequence: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	convex_hull_agg: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	corr: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	cos: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	cosh: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	cosine_distance: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	cosine_similarity: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	count: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	count_if: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	covar_pop: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	covar_samp: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	crc32: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	cume_dist: { docUrl: "https://trino.io/docs/current/functions/window.html", origin: "vendor-docs" },
	current_timezone: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	date: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	date_add: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	date_diff: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	date_format: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	date_parse: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	date_trunc: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	day: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	day_of_month: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	day_of_week: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	day_of_year: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	degrees: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	dense_rank: { docUrl: "https://trino.io/docs/current/functions/window.html", origin: "vendor-docs" },
	dow: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	doy: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	e: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	empty_approx_set: { docUrl: "https://trino.io/docs/current/functions/hyperloglog.html", origin: "vendor-docs" },
	ends_with: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	every: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	exp: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	features: { docUrl: "https://trino.io/docs/current/functions/ml.html", origin: "vendor-docs" },
	first_value: { docUrl: "https://trino.io/docs/current/functions/window.html", origin: "vendor-docs" },
	flatten: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	floor: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	format: { docUrl: "https://trino.io/docs/current/functions/conversion.html", origin: "vendor-docs" },
	format_datetime: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	format_number: { docUrl: "https://trino.io/docs/current/functions/conversion.html", origin: "vendor-docs" },
	from_base: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	from_base32: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	from_base64: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	from_base64url: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	from_big_endian_32: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	from_big_endian_64: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	from_encoded_polyline: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	from_geojson_geometry: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	from_hex: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	from_ieee754_32: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	from_ieee754_64: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	from_iso8601_date: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	from_iso8601_timestamp: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	from_iso8601_timestamp_nanos: {
		docUrl: "https://trino.io/docs/current/functions/datetime.html",
		origin: "vendor-docs",
	},
	from_unixtime: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	from_unixtime_nanos: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	from_utf8: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	geometric_mean: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	geometry_from_hadoop_shape: {
		docUrl: "https://trino.io/docs/current/functions/geospatial.html",
		origin: "vendor-docs",
	},
	geometry_invalid_reason: {
		docUrl: "https://trino.io/docs/current/functions/geospatial.html",
		origin: "vendor-docs",
	},
	geometry_nearest_points: {
		docUrl: "https://trino.io/docs/current/functions/geospatial.html",
		origin: "vendor-docs",
	},
	geometry_to_bing_tiles: {
		docUrl: "https://trino.io/docs/current/functions/geospatial.html",
		origin: "vendor-docs",
	},
	geometry_union_agg: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	great_circle_distance: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	hamming_distance: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	hash_counts: { docUrl: "https://trino.io/docs/current/functions/setdigest.html", origin: "vendor-docs" },
	histogram: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	hmac_md5: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	hmac_sha1: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	hmac_sha256: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	hmac_sha512: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	hour: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	human_readable_seconds: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	if: { docUrl: "https://trino.io/docs/current/functions/conditional.html", origin: "vendor-docs" },
	index: { docUrl: "https://trino.io/docs/current/functions/teradata.html", origin: "vendor-docs" },
	infinity: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	intersection_cardinality: {
		docUrl: "https://trino.io/docs/current/functions/setdigest.html",
		origin: "vendor-docs",
	},
	inverse_beta_cdf: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	inverse_normal_cdf: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	is_finite: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	is_infinite: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	is_json_scalar: { docUrl: "https://trino.io/docs/current/functions/json.html", origin: "vendor-docs" },
	is_nan: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	jaccard_index: { docUrl: "https://trino.io/docs/current/functions/setdigest.html", origin: "vendor-docs" },
	json_array_contains: { docUrl: "https://trino.io/docs/current/functions/json.html", origin: "vendor-docs" },
	json_array_get: { docUrl: "https://trino.io/docs/current/functions/json.html", origin: "vendor-docs" },
	json_array_length: { docUrl: "https://trino.io/docs/current/functions/json.html", origin: "vendor-docs" },
	json_extract: { docUrl: "https://trino.io/docs/current/functions/json.html", origin: "vendor-docs" },
	json_extract_scalar: { docUrl: "https://trino.io/docs/current/functions/json.html", origin: "vendor-docs" },
	json_format: { docUrl: "https://trino.io/docs/current/functions/json.html", origin: "vendor-docs" },
	json_parse: { docUrl: "https://trino.io/docs/current/functions/json.html", origin: "vendor-docs" },
	json_size: { docUrl: "https://trino.io/docs/current/functions/json.html", origin: "vendor-docs" },
	kurtosis: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	lag: { docUrl: "https://trino.io/docs/current/functions/window.html", origin: "vendor-docs" },
	last_day_of_month: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	last_value: { docUrl: "https://trino.io/docs/current/functions/window.html", origin: "vendor-docs" },
	lead: { docUrl: "https://trino.io/docs/current/functions/window.html", origin: "vendor-docs" },
	learn_classifier: { docUrl: "https://trino.io/docs/current/functions/ml.html", origin: "vendor-docs" },
	learn_libsvm_classifier: { docUrl: "https://trino.io/docs/current/functions/ml.html", origin: "vendor-docs" },
	learn_libsvm_regressor: { docUrl: "https://trino.io/docs/current/functions/ml.html", origin: "vendor-docs" },
	learn_regressor: { docUrl: "https://trino.io/docs/current/functions/ml.html", origin: "vendor-docs" },
	length: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	levenshtein_distance: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	line_interpolate_point: {
		docUrl: "https://trino.io/docs/current/functions/geospatial.html",
		origin: "vendor-docs",
	},
	line_interpolate_points: {
		docUrl: "https://trino.io/docs/current/functions/geospatial.html",
		origin: "vendor-docs",
	},
	line_locate_point: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	ln: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	log: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	log10: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	log2: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	lower: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	lpad: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	ltrim: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	luhn_check: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	make_set_digest: { docUrl: "https://trino.io/docs/current/functions/setdigest.html", origin: "vendor-docs" },
	map_agg: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	max: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	max_by: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	md5: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	merge: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	merge_set_digest: { docUrl: "https://trino.io/docs/current/functions/setdigest.html", origin: "vendor-docs" },
	millisecond: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	min: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	min_by: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	minute: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	mod: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	month: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	multimap_agg: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	murmur3: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	nan: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	normal_cdf: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	normalize: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	now: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	nth_value: { docUrl: "https://trino.io/docs/current/functions/window.html", origin: "vendor-docs" },
	ntile: { docUrl: "https://trino.io/docs/current/functions/window.html", origin: "vendor-docs" },
	nullif: { docUrl: "https://trino.io/docs/current/functions/conditional.html", origin: "vendor-docs" },
	numeric_histogram: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	parse_data_size: { docUrl: "https://trino.io/docs/current/functions/conversion.html", origin: "vendor-docs" },
	parse_datetime: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	parse_duration: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	percent_rank: { docUrl: "https://trino.io/docs/current/functions/window.html", origin: "vendor-docs" },
	pi: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	pow: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	power: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	qdigest_agg: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	quarter: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	radians: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	rand: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	random: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	rank: { docUrl: "https://trino.io/docs/current/functions/window.html", origin: "vendor-docs" },
	regexp_count: { docUrl: "https://trino.io/docs/current/functions/regexp.html", origin: "vendor-docs" },
	regexp_extract: { docUrl: "https://trino.io/docs/current/functions/regexp.html", origin: "vendor-docs" },
	regexp_extract_all: { docUrl: "https://trino.io/docs/current/functions/regexp.html", origin: "vendor-docs" },
	regexp_like: { docUrl: "https://trino.io/docs/current/functions/regexp.html", origin: "vendor-docs" },
	regexp_position: { docUrl: "https://trino.io/docs/current/functions/regexp.html", origin: "vendor-docs" },
	regexp_replace: { docUrl: "https://trino.io/docs/current/functions/regexp.html", origin: "vendor-docs" },
	regexp_split: { docUrl: "https://trino.io/docs/current/functions/regexp.html", origin: "vendor-docs" },
	regr_intercept: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	regr_slope: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	regress: { docUrl: "https://trino.io/docs/current/functions/ml.html", origin: "vendor-docs" },
	render: { docUrl: "https://trino.io/docs/current/functions/color.html", origin: "vendor-docs" },
	repeat: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	replace: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	reverse: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	rgb: { docUrl: "https://trino.io/docs/current/functions/color.html", origin: "vendor-docs" },
	round: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	row_number: { docUrl: "https://trino.io/docs/current/functions/window.html", origin: "vendor-docs" },
	rpad: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	rtrim: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	second: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	sequence: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	sha1: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	sha256: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	sha512: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	shuffle: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	sign: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	simplify_geometry: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	sin: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	sinh: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	skewness: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	slice: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	soundex: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	split: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	split_part: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	split_to_map: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	split_to_multimap: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	spooky_hash_v2_32: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	spooky_hash_v2_64: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	sqrt: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	st_area: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_asbinary: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_astext: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_boundary: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_buffer: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_centroid: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_contains: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_convexhull: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_coorddim: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_crosses: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_difference: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_dimension: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_disjoint: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_distance: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_endpoint: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_envelope: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_envelopeaspts: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_equals: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_exteriorring: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_geometries: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_geometryfromtext: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_geometryn: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_geometrytype: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_geomfrombinary: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_geomfromkml: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_interiorringn: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_interiorrings: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_intersection: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_intersects: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_isclosed: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_isempty: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_isring: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_issimple: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_isvalid: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_length: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_linefromtext: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_numgeometries: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_numinteriorring: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_numpoints: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_overlaps: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_point: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_pointn: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_points: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_polygon: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_relate: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_startpoint: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_symdifference: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_touches: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_union: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_within: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_x: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_xmax: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_xmin: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_y: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_ymax: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	st_ymin: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	starts_with: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	stddev: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	stddev_pop: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	stddev_samp: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	strpos: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	substr: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	substring: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	sum: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	t_cdf: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	t_pdf: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	tan: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	tanh: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	tdigest_agg: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	theta_sketch_cardinality: {
		docUrl: "https://trino.io/docs/current/functions/datasketches.html",
		origin: "vendor-docs",
	},
	timezone_hour: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	timezone_minute: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	to_base: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	to_base32: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	to_base64: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	to_base64url: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	to_big_endian_32: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	to_big_endian_64: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	to_char: { docUrl: "https://trino.io/docs/current/functions/teradata.html", origin: "vendor-docs" },
	to_date: { docUrl: "https://trino.io/docs/current/functions/teradata.html", origin: "vendor-docs" },
	to_encoded_polyline: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	to_geojson_geometry: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	to_geometry: { docUrl: "https://trino.io/docs/current/functions/geospatial.html", origin: "vendor-docs" },
	to_hex: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	to_ieee754_32: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	to_ieee754_64: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	to_iso8601: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	to_milliseconds: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	to_spherical_geography: {
		docUrl: "https://trino.io/docs/current/functions/geospatial.html",
		origin: "vendor-docs",
	},
	to_timestamp: { docUrl: "https://trino.io/docs/current/functions/teradata.html", origin: "vendor-docs" },
	to_unixtime: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	to_utf8: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	trim: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	trim_array: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
	truncate: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	try: { docUrl: "https://trino.io/docs/current/functions/conditional.html", origin: "vendor-docs" },
	typeof: { docUrl: "https://trino.io/docs/current/functions/conversion.html", origin: "vendor-docs" },
	upper: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	url_decode: { docUrl: "https://trino.io/docs/current/functions/url.html", origin: "vendor-docs" },
	url_encode: { docUrl: "https://trino.io/docs/current/functions/url.html", origin: "vendor-docs" },
	url_extract_fragment: { docUrl: "https://trino.io/docs/current/functions/url.html", origin: "vendor-docs" },
	url_extract_host: { docUrl: "https://trino.io/docs/current/functions/url.html", origin: "vendor-docs" },
	url_extract_parameter: { docUrl: "https://trino.io/docs/current/functions/url.html", origin: "vendor-docs" },
	url_extract_path: { docUrl: "https://trino.io/docs/current/functions/url.html", origin: "vendor-docs" },
	url_extract_port: { docUrl: "https://trino.io/docs/current/functions/url.html", origin: "vendor-docs" },
	url_extract_protocol: { docUrl: "https://trino.io/docs/current/functions/url.html", origin: "vendor-docs" },
	url_extract_query: { docUrl: "https://trino.io/docs/current/functions/url.html", origin: "vendor-docs" },
	uuid: { docUrl: "https://trino.io/docs/current/functions/uuid.html", origin: "vendor-docs" },
	value_at_quantile: { docUrl: "https://trino.io/docs/current/functions/tdigest.html", origin: "vendor-docs" },
	values_at_quantiles: { docUrl: "https://trino.io/docs/current/functions/tdigest.html", origin: "vendor-docs" },
	var_pop: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	var_samp: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	variance: { docUrl: "https://trino.io/docs/current/functions/aggregate.html", origin: "vendor-docs" },
	variant_is_null: { docUrl: "https://trino.io/docs/current/functions/variant.html", origin: "vendor-docs" },
	version: { docUrl: "https://trino.io/docs/current/functions/system.html", origin: "vendor-docs" },
	week: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	week_of_year: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	width_bucket: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	wilson_interval_lower: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	wilson_interval_upper: { docUrl: "https://trino.io/docs/current/functions/math.html", origin: "vendor-docs" },
	word_stem: { docUrl: "https://trino.io/docs/current/functions/string.html", origin: "vendor-docs" },
	xxhash64: { docUrl: "https://trino.io/docs/current/functions/binary.html", origin: "vendor-docs" },
	year: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	year_of_week: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	yow: { docUrl: "https://trino.io/docs/current/functions/datetime.html", origin: "vendor-docs" },
	zip: { docUrl: "https://trino.io/docs/current/functions/array.html", origin: "vendor-docs" },
};
