// GENERATED - do not edit by hand. Rebuild: node tools/harvest-signatures.mjs && npm run format
// The per-NAME function docs table for postgres (issue #34), parallel to the signature table:
// docUrl points at the vendor's published page for the same source the signature harvest read;
// description (where present) is origin-tagged prose. Same lowercased-name keys as *_SIGNATURES.
// Built 2026-07-14. 585 names (0 with descriptions).
import type { FnDoc } from "../signature/docs.js";

export const POSTGRES_FN_DOCS: Record<string, FnDoc> = {
	abbrev: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	acldefault: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	aclexplode: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	acos: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	acosd: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	acosh: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	age: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	any_value: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	area: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	array_append: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_cat: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_dims: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_fill: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_length: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_lower: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_ndims: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_position: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_positions: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_prepend: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_remove: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_replace: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_reverse: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_sample: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_shuffle: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_sort: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_to_json: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	array_to_string: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	array_to_tsvector: {
		docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html",
		origin: "vendor-docs",
	},
	array_upper: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	ascii: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	asin: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	asind: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	asinh: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	atan: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	atan2: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	atan2d: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	atand: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	atanh: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	avg: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	bit_and: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	bit_count: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	bit_length: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	bit_or: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	bit_xor: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	bool_and: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	bool_or: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	bound_box: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	box: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	brin_desummarize_range: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	brin_summarize_new_values: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	brin_summarize_range: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	broadcast: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	btrim: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	cardinality: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	casefold: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	cbrt: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	ceil: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	ceiling: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	center: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	char_length: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	character_length: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	chr: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	circle: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	clock_timestamp: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	coalesce: { docUrl: "https://www.postgresql.org/docs/18/functions-conditional.html", origin: "vendor-docs" },
	col_description: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	concat: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	concat_ws: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	convert: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	convert_from: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	convert_to: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	corr: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	cos: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	cosd: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	cosh: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	cot: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	cotd: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	covar_pop: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	covar_samp: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	crc32: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	crc32c: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	cume_dist: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	current_catalog: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	current_database: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	current_date: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	current_query: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	current_role: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	current_schema: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	current_schemas: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	current_setting: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	current_time: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	current_timestamp: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	current_user: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	currval: { docUrl: "https://www.postgresql.org/docs/18/functions-sequence.html", origin: "vendor-docs" },
	date_add: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	date_part: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	date_subtract: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	date_trunc: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	decode: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	degrees: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	dense_rank: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	diagonal: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	diameter: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	div: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	encode: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	enum_first: { docUrl: "https://www.postgresql.org/docs/18/functions-enum.html", origin: "vendor-docs" },
	enum_last: { docUrl: "https://www.postgresql.org/docs/18/functions-enum.html", origin: "vendor-docs" },
	enum_range: { docUrl: "https://www.postgresql.org/docs/18/functions-enum.html", origin: "vendor-docs" },
	erf: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	erfc: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	every: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	exp: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	factorial: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	family: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	first_value: { docUrl: "https://www.postgresql.org/docs/18/functions-window.html", origin: "vendor-docs" },
	floor: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	format: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	format_type: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	gamma: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	gcd: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	gen_random_uuid: { docUrl: "https://www.postgresql.org/docs/18/functions-uuid.html", origin: "vendor-docs" },
	generate_series: { docUrl: "https://www.postgresql.org/docs/18/functions-srf.html", origin: "vendor-docs" },
	generate_subscripts: { docUrl: "https://www.postgresql.org/docs/18/functions-srf.html", origin: "vendor-docs" },
	get_bit: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	get_byte: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	get_current_ts_config: {
		docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html",
		origin: "vendor-docs",
	},
	gin_clean_pending_list: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	greatest: { docUrl: "https://www.postgresql.org/docs/18/functions-conditional.html", origin: "vendor-docs" },
	grouping: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	height: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	host: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	hostmask: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	icu_unicode_version: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	inet_client_addr: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	inet_client_port: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	inet_merge: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	inet_same_family: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	inet_server_addr: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	inet_server_port: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	initcap: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	isclosed: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	isempty: { docUrl: "https://www.postgresql.org/docs/18/functions-range.html", origin: "vendor-docs" },
	isfinite: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	isopen: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	json_agg_strict: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	json_array_elements: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_array_elements_text: {
		docUrl: "https://www.postgresql.org/docs/18/functions-json.html",
		origin: "vendor-docs",
	},
	json_array_length: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_build_array: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_each: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_each_text: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_extract_path: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_extract_path_text: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_object: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_object_agg_strict: {
		docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html",
		origin: "vendor-docs",
	},
	json_object_agg_unique: {
		docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html",
		origin: "vendor-docs",
	},
	json_object_agg_unique_strict: {
		docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html",
		origin: "vendor-docs",
	},
	json_object_keys: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_populate_record: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_populate_recordset: {
		docUrl: "https://www.postgresql.org/docs/18/functions-json.html",
		origin: "vendor-docs",
	},
	json_scalar: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_strip_nulls: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_to_record: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_to_recordset: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	json_typeof: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_agg_strict: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	jsonb_array_elements: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_array_elements_text: {
		docUrl: "https://www.postgresql.org/docs/18/functions-json.html",
		origin: "vendor-docs",
	},
	jsonb_array_length: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_build_array: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_build_object: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_each: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_each_text: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_extract_path: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_extract_path_text: {
		docUrl: "https://www.postgresql.org/docs/18/functions-json.html",
		origin: "vendor-docs",
	},
	jsonb_insert: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_object: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_object_agg_strict: {
		docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html",
		origin: "vendor-docs",
	},
	jsonb_object_agg_unique: {
		docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html",
		origin: "vendor-docs",
	},
	jsonb_object_agg_unique_strict: {
		docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html",
		origin: "vendor-docs",
	},
	jsonb_object_keys: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_path_exists: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_path_exists_tz: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_path_match: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_path_match_tz: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_path_query: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_path_query_array: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_path_query_array_tz: {
		docUrl: "https://www.postgresql.org/docs/18/functions-json.html",
		origin: "vendor-docs",
	},
	jsonb_path_query_first: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_path_query_first_tz: {
		docUrl: "https://www.postgresql.org/docs/18/functions-json.html",
		origin: "vendor-docs",
	},
	jsonb_path_query_tz: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_populate_record: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_populate_record_valid: {
		docUrl: "https://www.postgresql.org/docs/18/functions-json.html",
		origin: "vendor-docs",
	},
	jsonb_populate_recordset: {
		docUrl: "https://www.postgresql.org/docs/18/functions-json.html",
		origin: "vendor-docs",
	},
	jsonb_pretty: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_set: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_set_lax: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_strip_nulls: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_to_record: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_to_recordset: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	jsonb_typeof: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	justify_days: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	justify_hours: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	justify_interval: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	lag: { docUrl: "https://www.postgresql.org/docs/18/functions-window.html", origin: "vendor-docs" },
	last_value: { docUrl: "https://www.postgresql.org/docs/18/functions-window.html", origin: "vendor-docs" },
	lastval: { docUrl: "https://www.postgresql.org/docs/18/functions-sequence.html", origin: "vendor-docs" },
	lcm: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	lead: { docUrl: "https://www.postgresql.org/docs/18/functions-window.html", origin: "vendor-docs" },
	least: { docUrl: "https://www.postgresql.org/docs/18/functions-conditional.html", origin: "vendor-docs" },
	left: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	length: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	lgamma: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	line: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	ln: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	localtime: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	localtimestamp: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	log: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	log10: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	lower: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	lower_inc: { docUrl: "https://www.postgresql.org/docs/18/functions-range.html", origin: "vendor-docs" },
	lower_inf: { docUrl: "https://www.postgresql.org/docs/18/functions-range.html", origin: "vendor-docs" },
	lpad: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	lseg: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	ltrim: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	macaddr8_set7bit: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	make_date: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	make_interval: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	make_time: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	make_timestamp: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	make_timestamptz: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	makeaclitem: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	masklen: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	md5: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	merge_action: { docUrl: "https://www.postgresql.org/docs/18/functions-merge-support.html", origin: "vendor-docs" },
	min_scale: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	mod: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	mode: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	multirange: { docUrl: "https://www.postgresql.org/docs/18/functions-range.html", origin: "vendor-docs" },
	mxid_age: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	netmask: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	network: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	nextval: { docUrl: "https://www.postgresql.org/docs/18/functions-sequence.html", origin: "vendor-docs" },
	normalize: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	now: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	npoints: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	nth_value: { docUrl: "https://www.postgresql.org/docs/18/functions-window.html", origin: "vendor-docs" },
	ntile: { docUrl: "https://www.postgresql.org/docs/18/functions-window.html", origin: "vendor-docs" },
	nullif: { docUrl: "https://www.postgresql.org/docs/18/functions-conditional.html", origin: "vendor-docs" },
	num_nonnulls: { docUrl: "https://www.postgresql.org/docs/18/functions-comparison.html", origin: "vendor-docs" },
	num_nulls: { docUrl: "https://www.postgresql.org/docs/18/functions-comparison.html", origin: "vendor-docs" },
	numnode: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	obj_description: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	octet_length: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	path: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	pclose: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	percent_rank: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	percentile_cont: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	percentile_disc: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	pg_advisory_lock: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_advisory_lock_shared: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_advisory_unlock: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_advisory_unlock_all: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_advisory_unlock_shared: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_advisory_xact_lock: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_advisory_xact_lock_shared: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_available_wal_summaries: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_backend_pid: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_backup_start: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_backup_stop: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_basetype: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_blocking_pids: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_cancel_backend: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_char_to_encoding: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_clear_attribute_stats: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_clear_relation_stats: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_client_encoding: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	pg_collation_actual_version: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_collation_is_visible: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_column_compression: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_column_size: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_column_toast_chunk_id: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_conf_load_time: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_control_checkpoint: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_control_init: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_control_recovery: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_control_system: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_conversion_is_visible: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_copy_logical_replication_slot: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_copy_physical_replication_slot: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_create_restore_point: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_current_logfile: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_current_snapshot: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_current_wal_flush_lsn: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_current_wal_insert_lsn: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_current_wal_lsn: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_current_xact_id: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_current_xact_id_if_assigned: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_database_collation_actual_version: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_database_size: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_describe_object: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_drop_replication_slot: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_encoding_to_char: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_event_trigger_ddl_commands: {
		docUrl: "https://www.postgresql.org/docs/18/functions-event-triggers.html",
		origin: "vendor-docs",
	},
	pg_event_trigger_dropped_objects: {
		docUrl: "https://www.postgresql.org/docs/18/functions-event-triggers.html",
		origin: "vendor-docs",
	},
	pg_event_trigger_table_rewrite_oid: {
		docUrl: "https://www.postgresql.org/docs/18/functions-event-triggers.html",
		origin: "vendor-docs",
	},
	pg_event_trigger_table_rewrite_reason: {
		docUrl: "https://www.postgresql.org/docs/18/functions-event-triggers.html",
		origin: "vendor-docs",
	},
	pg_export_snapshot: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_filenode_relation: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_function_is_visible: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_acl: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_catalog_foreign_keys: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_get_constraintdef: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_expr: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_function_arguments: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_get_function_identity_arguments: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_get_function_result: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_functiondef: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_keywords: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_loaded_modules: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_multixact_members: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_get_object_address: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_partition_constraintdef: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_get_partkeydef: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_ruledef: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_serial_sequence: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_statisticsobjdef: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_get_triggerdef: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_userbyid: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_viewdef: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_get_wal_replay_pause_state: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_get_wal_resource_managers: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_get_wal_summarizer_state: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_identify_object: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_identify_object_as_address: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_import_system_collations: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_index_column_has_property: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_index_has_property: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_indexam_has_property: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_indexes_size: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_input_error_info: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_input_is_valid: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_is_in_recovery: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_is_other_temp_schema: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_is_wal_replay_paused: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_jit_available: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_last_committed_xact: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_last_wal_receive_lsn: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_last_wal_replay_lsn: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_last_xact_replay_timestamp: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_listening_channels: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_log_backend_memory_contexts: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_log_standby_snapshot: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_logical_slot_get_binary_changes: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_logical_slot_get_changes: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_logical_slot_peek_binary_changes: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_logical_slot_peek_changes: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_ls_archive_statusdir: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_ls_logdir: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_ls_logicalmapdir: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_ls_logicalsnapdir: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_ls_replslotdir: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_ls_summariesdir: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_ls_tmpdir: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_ls_waldir: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_mcv_list_items: {
		docUrl: "https://www.postgresql.org/docs/18/functions-statistics.html",
		origin: "vendor-docs",
	},
	pg_my_temp_schema: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_notification_queue_usage: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_numa_available: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_opclass_is_visible: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_operator_is_visible: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_opfamily_is_visible: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_options_to_table: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_partition_ancestors: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_partition_root: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_partition_tree: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_postmaster_start_time: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_relation_filenode: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_relation_filepath: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_relation_size: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_reload_conf: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_replication_origin_advance: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_replication_origin_create: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_replication_origin_drop: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_replication_origin_oid: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_replication_origin_progress: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_replication_origin_session_is_setup: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_replication_origin_session_progress: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_replication_origin_session_reset: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_replication_origin_session_setup: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_replication_origin_xact_reset: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_replication_origin_xact_setup: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_replication_slot_advance: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_restore_attribute_stats: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_restore_relation_stats: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_rotate_logfile: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_safe_snapshot_blocking_pids: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_settings_get_flags: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_size_bytes: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_size_pretty: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_snapshot_xip: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_snapshot_xmax: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_snapshot_xmin: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_split_walfile_name: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_stat_file: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_statistics_obj_is_visible: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_switch_wal: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_sync_replication_slots: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_table_is_visible: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_table_size: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_tablespace_databases: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_tablespace_location: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_tablespace_size: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_total_relation_size: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_trigger_depth: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_try_advisory_lock: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_try_advisory_lock_shared: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_try_advisory_xact_lock: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_try_advisory_xact_lock_shared: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_ts_config_is_visible: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_ts_dict_is_visible: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_ts_parser_is_visible: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_ts_template_is_visible: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_type_is_visible: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_typeof: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_visible_in_snapshot: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pg_wal_lsn_diff: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_wal_replay_pause: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_wal_replay_resume: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_wal_summary_contents: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_walfile_name: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	pg_walfile_name_offset: {
		docUrl: "https://www.postgresql.org/docs/18/functions-admin.html",
		origin: "vendor-docs",
	},
	pg_xact_commit_timestamp: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_xact_commit_timestamp_origin: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	pg_xact_status: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	pi: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	point: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	polygon: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	popen: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	power: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	querytree: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	quote_ident: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	quote_literal: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	quote_nullable: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	radians: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	radius: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	random: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	random_normal: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	range_agg: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	range_intersect_agg: {
		docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html",
		origin: "vendor-docs",
	},
	range_merge: { docUrl: "https://www.postgresql.org/docs/18/functions-range.html", origin: "vendor-docs" },
	rank: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	regexp_count: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	regexp_instr: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	regexp_like: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	regexp_match: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	regexp_matches: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	regexp_replace: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	regexp_split_to_array: {
		docUrl: "https://www.postgresql.org/docs/18/functions-string.html",
		origin: "vendor-docs",
	},
	regexp_split_to_table: {
		docUrl: "https://www.postgresql.org/docs/18/functions-string.html",
		origin: "vendor-docs",
	},
	regexp_substr: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	regr_avgx: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	regr_avgy: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	regr_count: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	regr_intercept: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	regr_r2: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	regr_slope: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	regr_sxx: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	regr_sxy: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	regr_syy: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	repeat: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	replace: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	reverse: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	right: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	round: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	row_number: { docUrl: "https://www.postgresql.org/docs/18/functions-window.html", origin: "vendor-docs" },
	row_to_json: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	rpad: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	rtrim: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	scale: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	session_user: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	set_bit: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	set_byte: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	set_config: { docUrl: "https://www.postgresql.org/docs/18/functions-admin.html", origin: "vendor-docs" },
	set_masklen: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	setseed: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	setval: { docUrl: "https://www.postgresql.org/docs/18/functions-sequence.html", origin: "vendor-docs" },
	setweight: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	sha224: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	sha256: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	sha384: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	sha512: { docUrl: "https://www.postgresql.org/docs/18/functions-binarystring.html", origin: "vendor-docs" },
	shobj_description: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	sign: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	sin: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	sind: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	sinh: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	slope: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	split_part: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	sqrt: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	starts_with: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	statement_timestamp: {
		docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html",
		origin: "vendor-docs",
	},
	stddev: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	stddev_pop: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	stddev_samp: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	string_agg: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	string_to_array: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	string_to_table: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	strip: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	strpos: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	substr: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	sum: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	suppress_redundant_updates_trigger: {
		docUrl: "https://www.postgresql.org/docs/18/functions-trigger.html",
		origin: "vendor-docs",
	},
	system_user: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	tan: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	tand: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	tanh: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	text: { docUrl: "https://www.postgresql.org/docs/18/functions-net.html", origin: "vendor-docs" },
	timeofday: { docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html", origin: "vendor-docs" },
	to_ascii: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	to_bin: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	to_char: { docUrl: "https://www.postgresql.org/docs/18/functions-formatting.html", origin: "vendor-docs" },
	to_hex: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	to_json: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	to_jsonb: { docUrl: "https://www.postgresql.org/docs/18/functions-json.html", origin: "vendor-docs" },
	to_oct: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	to_regclass: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	to_regcollation: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	to_regnamespace: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	to_regoper: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	to_regoperator: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	to_regproc: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	to_regprocedure: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	to_regrole: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	to_regtype: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	to_regtypemod: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	to_timestamp: { docUrl: "https://www.postgresql.org/docs/18/functions-formatting.html", origin: "vendor-docs" },
	transaction_timestamp: {
		docUrl: "https://www.postgresql.org/docs/18/functions-datetime.html",
		origin: "vendor-docs",
	},
	translate: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	trim_array: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	trim_scale: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	trunc: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	ts_delete: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	ts_filter: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	ts_lexize: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	ts_parse: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	ts_rewrite: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	ts_stat: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	ts_token_type: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	tsquery_phrase: { docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html", origin: "vendor-docs" },
	tsvector_to_array: {
		docUrl: "https://www.postgresql.org/docs/18/functions-textsearch.html",
		origin: "vendor-docs",
	},
	tsvector_update_trigger: {
		docUrl: "https://www.postgresql.org/docs/18/functions-trigger.html",
		origin: "vendor-docs",
	},
	tsvector_update_trigger_column: {
		docUrl: "https://www.postgresql.org/docs/18/functions-trigger.html",
		origin: "vendor-docs",
	},
	txid_current: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	txid_current_if_assigned: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	txid_current_snapshot: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	txid_snapshot_xip: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	txid_snapshot_xmax: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	txid_snapshot_xmin: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	txid_status: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	txid_visible_in_snapshot: {
		docUrl: "https://www.postgresql.org/docs/18/functions-info.html",
		origin: "vendor-docs",
	},
	unicode_assigned: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	unicode_version: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	unistr: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	unnest: { docUrl: "https://www.postgresql.org/docs/18/functions-array.html", origin: "vendor-docs" },
	upper: { docUrl: "https://www.postgresql.org/docs/18/functions-string.html", origin: "vendor-docs" },
	upper_inc: { docUrl: "https://www.postgresql.org/docs/18/functions-range.html", origin: "vendor-docs" },
	upper_inf: { docUrl: "https://www.postgresql.org/docs/18/functions-range.html", origin: "vendor-docs" },
	user: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	uuid_extract_timestamp: { docUrl: "https://www.postgresql.org/docs/18/functions-uuid.html", origin: "vendor-docs" },
	uuid_extract_version: { docUrl: "https://www.postgresql.org/docs/18/functions-uuid.html", origin: "vendor-docs" },
	uuidv4: { docUrl: "https://www.postgresql.org/docs/18/functions-uuid.html", origin: "vendor-docs" },
	uuidv7: { docUrl: "https://www.postgresql.org/docs/18/functions-uuid.html", origin: "vendor-docs" },
	var_pop: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	var_samp: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	variance: { docUrl: "https://www.postgresql.org/docs/18/functions-aggregate.html", origin: "vendor-docs" },
	version: { docUrl: "https://www.postgresql.org/docs/18/functions-info.html", origin: "vendor-docs" },
	width: { docUrl: "https://www.postgresql.org/docs/18/functions-geometry.html", origin: "vendor-docs" },
	width_bucket: { docUrl: "https://www.postgresql.org/docs/18/functions-math.html", origin: "vendor-docs" },
	xmlagg: { docUrl: "https://www.postgresql.org/docs/18/functions-xml.html", origin: "vendor-docs" },
	xmlcomment: { docUrl: "https://www.postgresql.org/docs/18/functions-xml.html", origin: "vendor-docs" },
	xmlconcat: { docUrl: "https://www.postgresql.org/docs/18/functions-xml.html", origin: "vendor-docs" },
	xmltext: { docUrl: "https://www.postgresql.org/docs/18/functions-xml.html", origin: "vendor-docs" },
	xpath: { docUrl: "https://www.postgresql.org/docs/18/functions-xml.html", origin: "vendor-docs" },
	xpath_exists: { docUrl: "https://www.postgresql.org/docs/18/functions-xml.html", origin: "vendor-docs" },
};
