// GENERATED - do not edit by hand. Rebuild: node tools/harvest-signatures.mjs && npm run format
// The per-NAME function docs table for mysql (issue #34), parallel to the signature table:
// docUrl points at the vendor's published page for the same source the signature harvest read;
// description (where present) is origin-tagged prose. Same lowercased-name keys as *_SIGNATURES.
// Built 2026-07-14. 241 names (0 with descriptions).
import type { FnDoc } from "../signature/docs.js";

export const MYSQL_FN_DOCS: Record<string, FnDoc> = {
	abs: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	acos: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	adddate: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	addtime: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	any_value: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html",
		origin: "vendor-docs",
	},
	ascii: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	asin: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	atan: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	atan2: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	avg: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	benchmark: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html", origin: "vendor-docs" },
	bin: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	bin_to_uuid: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html",
		origin: "vendor-docs",
	},
	bit_and: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	bit_count: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/bit-functions.html", origin: "vendor-docs" },
	bit_length: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	bit_or: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	bit_xor: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	ceil: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	ceiling: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	char_length: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	character_length: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html",
		origin: "vendor-docs",
	},
	charset: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html", origin: "vendor-docs" },
	coalesce: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/comparison-operators.html", origin: "vendor-docs" },
	coercibility: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html",
		origin: "vendor-docs",
	},
	collation: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html", origin: "vendor-docs" },
	compress: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html", origin: "vendor-docs" },
	concat: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	concat_ws: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	connection_id: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html",
		origin: "vendor-docs",
	},
	conv: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	convert: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/cast-functions.html", origin: "vendor-docs" },
	convert_tz: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	cos: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	cot: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	count: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	crc32: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	cume_dist: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html",
		origin: "vendor-docs",
	},
	curdate: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	current_date: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	current_role: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html",
		origin: "vendor-docs",
	},
	current_time: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	current_timestamp: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	current_user: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html",
		origin: "vendor-docs",
	},
	curtime: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	database: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html", origin: "vendor-docs" },
	date: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	date_format: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	datediff: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	day: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	dayname: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	dayofmonth: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	dayofweek: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	dayofyear: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	default: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html", origin: "vendor-docs" },
	degrees: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	dense_rank: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html",
		origin: "vendor-docs",
	},
	elt: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	exp: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	export_set: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	field: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	find_in_set: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	first_value: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html",
		origin: "vendor-docs",
	},
	floor: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	format: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	found_rows: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html", origin: "vendor-docs" },
	from_base64: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	from_days: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	from_unixtime: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	get_lock: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/locking-functions.html", origin: "vendor-docs" },
	greatest: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/comparison-operators.html", origin: "vendor-docs" },
	group_concat: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	hex: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	hour: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	icu_version: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html",
		origin: "vendor-docs",
	},
	if: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/flow-control-functions.html", origin: "vendor-docs" },
	ifnull: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/flow-control-functions.html", origin: "vendor-docs" },
	inet6_aton: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html",
		origin: "vendor-docs",
	},
	inet6_ntoa: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html",
		origin: "vendor-docs",
	},
	inet_aton: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html",
		origin: "vendor-docs",
	},
	inet_ntoa: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html",
		origin: "vendor-docs",
	},
	insert: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	instr: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	interval: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/comparison-operators.html", origin: "vendor-docs" },
	is_free_lock: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/locking-functions.html", origin: "vendor-docs" },
	is_ipv4: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html", origin: "vendor-docs" },
	is_ipv4_compat: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html",
		origin: "vendor-docs",
	},
	is_ipv4_mapped: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html",
		origin: "vendor-docs",
	},
	is_ipv6: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html", origin: "vendor-docs" },
	is_used_lock: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/locking-functions.html", origin: "vendor-docs" },
	is_uuid: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html", origin: "vendor-docs" },
	isnull: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/comparison-operators.html", origin: "vendor-docs" },
	json_arrayagg: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html",
		origin: "vendor-docs",
	},
	json_contains: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-search-functions.html",
		origin: "vendor-docs",
	},
	json_depth: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-attribute-functions.html",
		origin: "vendor-docs",
	},
	json_keys: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-search-functions.html", origin: "vendor-docs" },
	json_length: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-attribute-functions.html",
		origin: "vendor-docs",
	},
	json_objectagg: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html",
		origin: "vendor-docs",
	},
	json_overlaps: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-search-functions.html",
		origin: "vendor-docs",
	},
	json_pretty: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-utility-functions.html",
		origin: "vendor-docs",
	},
	json_quote: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-creation-functions.html",
		origin: "vendor-docs",
	},
	json_schema_valid: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-validation-functions.html",
		origin: "vendor-docs",
	},
	json_schema_validation_report: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-validation-functions.html",
		origin: "vendor-docs",
	},
	json_storage_free: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-utility-functions.html",
		origin: "vendor-docs",
	},
	json_storage_size: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-utility-functions.html",
		origin: "vendor-docs",
	},
	json_type: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-attribute-functions.html",
		origin: "vendor-docs",
	},
	json_unquote: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-modification-functions.html",
		origin: "vendor-docs",
	},
	json_valid: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-attribute-functions.html",
		origin: "vendor-docs",
	},
	json_value: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/json-search-functions.html", origin: "vendor-docs" },
	lag: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html", origin: "vendor-docs" },
	last_day: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	last_insert_id: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html",
		origin: "vendor-docs",
	},
	last_value: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html",
		origin: "vendor-docs",
	},
	lcase: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	lead: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html",
		origin: "vendor-docs",
	},
	least: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/comparison-operators.html", origin: "vendor-docs" },
	left: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	length: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	ln: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	load_file: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	localtime: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	localtimestamp: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	locate: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	log: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	log10: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	log2: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	lower: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	lpad: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	ltrim: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	make_set: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	makedate: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	maketime: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	max: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	md5: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html", origin: "vendor-docs" },
	microsecond: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	mid: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	min: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	minute: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	mod: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	month: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	monthname: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	name_const: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html",
		origin: "vendor-docs",
	},
	now: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	nth_value: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html",
		origin: "vendor-docs",
	},
	ntile: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html",
		origin: "vendor-docs",
	},
	nullif: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/flow-control-functions.html", origin: "vendor-docs" },
	oct: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	octet_length: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	ord: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	percent_rank: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html",
		origin: "vendor-docs",
	},
	period_add: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	period_diff: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	pi: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	pow: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	power: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	quarter: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	quote: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	radians: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	rand: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	random_bytes: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html",
		origin: "vendor-docs",
	},
	rank: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html",
		origin: "vendor-docs",
	},
	regexp_instr: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/regexp.html", origin: "vendor-docs" },
	regexp_like: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/regexp.html", origin: "vendor-docs" },
	regexp_replace: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/regexp.html", origin: "vendor-docs" },
	regexp_substr: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/regexp.html", origin: "vendor-docs" },
	release_all_locks: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/locking-functions.html",
		origin: "vendor-docs",
	},
	release_lock: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/locking-functions.html", origin: "vendor-docs" },
	repeat: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	replace: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	reverse: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	right: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	roles_graphml: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html",
		origin: "vendor-docs",
	},
	round: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	row_count: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html", origin: "vendor-docs" },
	row_number: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html",
		origin: "vendor-docs",
	},
	rpad: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	rtrim: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	schema: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html", origin: "vendor-docs" },
	sec_to_time: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	second: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	session_user: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html",
		origin: "vendor-docs",
	},
	sha: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html", origin: "vendor-docs" },
	sha1: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html", origin: "vendor-docs" },
	sha2: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html", origin: "vendor-docs" },
	sign: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	sin: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	sleep: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html", origin: "vendor-docs" },
	soundex: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	space: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	sqrt: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	statement_digest: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html",
		origin: "vendor-docs",
	},
	statement_digest_text: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html",
		origin: "vendor-docs",
	},
	std: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	stddev: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	stddev_pop: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	stddev_samp: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	str_to_date: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	subdate: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	substr: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	substring: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	substring_index: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	subtime: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	sum: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	sysdate: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	system_user: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html",
		origin: "vendor-docs",
	},
	tan: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	time: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	time_format: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	time_to_sec: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	timediff: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	timestamp: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	timestampadd: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	timestampdiff: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	to_base64: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	to_days: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	to_seconds: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	truncate: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html", origin: "vendor-docs" },
	ucase: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	uncompress: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html", origin: "vendor-docs" },
	uncompressed_length: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html",
		origin: "vendor-docs",
	},
	unhex: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	unix_timestamp: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	upper: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/string-functions.html", origin: "vendor-docs" },
	user: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html", origin: "vendor-docs" },
	utc_date: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	utc_time: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	utc_timestamp: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	uuid: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html", origin: "vendor-docs" },
	uuid_short: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html",
		origin: "vendor-docs",
	},
	uuid_to_bin: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html",
		origin: "vendor-docs",
	},
	validate_password_strength: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html",
		origin: "vendor-docs",
	},
	values: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/miscellaneous-functions.html", origin: "vendor-docs" },
	var_pop: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	var_samp: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	variance: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html", origin: "vendor-docs" },
	version: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/information-functions.html", origin: "vendor-docs" },
	week: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	weekday: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	weekofyear: {
		docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html",
		origin: "vendor-docs",
	},
	year: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
	yearweek: { docUrl: "https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html", origin: "vendor-docs" },
};
